# Left-side rotary encoder candidates
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_POLLING=y
CONFIG_EC11_THREAD_STACK_SIZE=1024
CONFIG_EC11_THREAD_PRIORITY=10
CONFIG_EC11_POLLING_INTERVAL_MS=5
CONFIG_ZMK_INPUT_MODULE_SENSOR_PROXY_DIRECT_TRIGGER_HANDLER=n

# Left-side analog joystick candidate
CONFIG_ADC=y
CONFIG_ADC_ASYNC=y
CONFIG_ANALOG_INPUT=y
CONFIG_ANALOG_INPUT_LOG_LEVEL_DBG=y
CONFIG_ANALOG_INPUT_REPORT_INTERVAL_MIN=22
CONFIG_ANALOG_INPUT_LOG_DBG_RAW=n
CONFIG_ANALOG_INPUT_LOG_DBG_REPORT=n
CONFIG_DYA_ANALOG_INPUT=y
CONFIG_DYA_ANALOG_INPUT_STUDIO_RPC=y
CONFIG_ZMK_INPUT_MODULE_STUDIO_RPC=y

# Left-side interior input processor
CONFIG_ZMK_INPUT_PROCESSOR_KEYBIND=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y
