# Left-side rotary encoder candidates
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Left-side analog joystick candidate
CONFIG_ADC=y
CONFIG_ADC_ASYNC=y
CONFIG_ANALOG_INPUT=y
CONFIG_ANALOG_INPUT_LOG_LEVEL_DBG=y
CONFIG_ANALOG_INPUT_REPORT_INTERVAL_MIN=22
CONFIG_ANALOG_INPUT_LOG_DBG_RAW=n
CONFIG_ANALOG_INPUT_LOG_DBG_REPORT=n
CONFIG_DYA_ANALOG_INPUT=y
CONFIG_DYA_ANALOG_INPUT_STUDIO_RPC=y
CONFIG_ZMK_INPUT_MODULE_STUDIO_RPC=y

# Left-side interior input processor
CONFIG_ZMK_INPUT_PROCESSOR_KEYBIND=y
